Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
client = bigquery.Client(location="US", project="ubineerpoc")

# query = """
# SELECT MAX(reportingDate), financialEntity, coDescription FROM `ubineerpoc.10KData.10KBusinessDesc`
# GROUP BY financialEntity, coDescription
# LIMIT 500
# """
query = """
SELECT coDescription FROM `ubineerpoc.10KData.10KBusinessDesc` LIMIT 500
"""
query_job = client.query(query)  # API request - starts the query

df = query_job.to_dataframe()
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mDefaultCredentialsError[0m                   Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m client [38;5;241m=[39m [43mbigquery[49m[38;5;241;43m.[39;49m[43mClient[49m[43m([49m[43mlocation[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mUS[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mproject[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mubineerpoc[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      3[0m [38;5;66;03m# query = """[39;00m
[1;32m      4[0m [38;5;66;03m# SELECT MAX(reportingDate), financialEntity, coDescription FROM `ubineerpoc.10KData.10KBusinessDesc`[39;00m
[1;32m      5[0m [38;5;66;03m# GROUP BY financialEntity, coDescription[39;00m
[1;32m      6[0m [38;5;66;03m# LIMIT 500[39;00m
[1;32m      7[0m [38;5;66;03m# """[39;00m
[1;32m      8[0m query [38;5;241m=[39m [38;5;124m"""[39m
[1;32m      9[0m [38;5;124mSELECT coDescription FROM `ubineerpoc.10KData.10KBusinessDesc` LIMIT 500[39m
[1;32m     10[0m [38;5;124m"""[39m

File [0;32m/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py:231[0m, in [0;36mClient.__init__[0;34m(self, project, credentials, _http, location, default_query_job_config, client_info, client_options)[0m
[1;32m    221[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m(
[1;32m    222[0m     [38;5;28mself[39m,
[1;32m    223[0m     project[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m    229[0m     client_options[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    230[0m ):
[0;32m--> 231[0m     [38;5;28;43msuper[39;49m[43m([49m[43mClient[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m
[1;32m    232[0m [43m        [49m[43mproject[49m[38;5;241;43m=[39;49m[43mproject[49m[43m,[49m
[1;32m    233[0m [43m        [49m[43mcredentials[49m[38;5;241;43m=[39;49m[43mcredentials[49m[43m,[49m
[1;32m    234[0m [43m        [49m[43mclient_options[49m[38;5;241;43m=[39;49m[43mclient_options[49m[43m,[49m
[1;32m    235[0m [43m        [49m[43m_http[49m[38;5;241;43m=[39;49m[43m_http[49m[43m,[49m
[1;32m    236[0m [43m    [49m[43m)[49m
[1;32m    238[0m     kw_args [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mclient_info[39m[38;5;124m"[39m: client_info}
[1;32m    239[0m     [38;5;28;01mif[39;00m client_options:

File [0;32m/usr/local/lib/python3.9/site-packages/google/cloud/client/__init__.py:319[0m, in [0;36mClientWithProject.__init__[0;34m(self, project, credentials, client_options, _http)[0m
[1;32m    317[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, project[38;5;241m=[39m[38;5;28;01mNone[39;00m, credentials[38;5;241m=[39m[38;5;28;01mNone[39;00m, client_options[38;5;241m=[39m[38;5;28;01mNone[39;00m, _http[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m    318[0m     _ClientProjectMixin[38;5;241m.[39m[38;5;21m__init__[39m([38;5;28mself[39m, project[38;5;241m=[39mproject, credentials[38;5;241m=[39mcredentials)
[0;32m--> 319[0m     [43mClient[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m
[1;32m    320[0m [43m        [49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mcredentials[49m[38;5;241;43m=[39;49m[43mcredentials[49m[43m,[49m[43m [49m[43mclient_options[49m[38;5;241;43m=[39;49m[43mclient_options[49m[43m,[49m[43m [49m[43m_http[49m[38;5;241;43m=[39;49m[43m_http[49m
[1;32m    321[0m [43m    [49m[43m)[49m

File [0;32m/usr/local/lib/python3.9/site-packages/google/cloud/client/__init__.py:178[0m, in [0;36mClient.__init__[0;34m(self, credentials, _http, client_options)[0m
[1;32m    174[0m         credentials, _ [38;5;241m=[39m google[38;5;241m.[39mauth[38;5;241m.[39mload_credentials_from_file(
[1;32m    175[0m             client_options[38;5;241m.[39mcredentials_file, scopes[38;5;241m=[39mscopes
[1;32m    176[0m         )
[1;32m    177[0m     [38;5;28;01melse[39;00m:
[0;32m--> 178[0m         credentials, _ [38;5;241m=[39m [43mgoogle[49m[38;5;241;43m.[39;49m[43mauth[49m[38;5;241;43m.[39;49m[43mdefault[49m[43m([49m[43mscopes[49m[38;5;241;43m=[39;49m[43mscopes[49m[43m)[49m
[1;32m    180[0m [38;5;28mself[39m[38;5;241m.[39m_credentials [38;5;241m=[39m google[38;5;241m.[39mauth[38;5;241m.[39mcredentials[38;5;241m.[39mwith_scopes_if_required(
[1;32m    181[0m     credentials, scopes[38;5;241m=[39mscopes
[1;32m    182[0m )
[1;32m    184[0m [38;5;28;01mif[39;00m client_options[38;5;241m.[39mquota_project_id:

File [0;32m/usr/local/lib/python3.9/site-packages/google/auth/_default.py:575[0m, in [0;36mdefault[0;34m(scopes, request, quota_project_id, default_scopes)[0m
[1;32m    567[0m             _LOGGER[38;5;241m.[39mwarning(
[1;32m    568[0m                 [38;5;124m"[39m[38;5;124mNo project ID could be determined. Consider running [39m[38;5;124m"[39m
[1;32m    569[0m                 [38;5;124m"[39m[38;5;124m`gcloud config set project` or setting the [39m[38;5;132;01m%s[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m    570[0m                 [38;5;124m"[39m[38;5;124menvironment variable[39m[38;5;124m"[39m,
[1;32m    571[0m                 environment_vars[38;5;241m.[39mPROJECT,
[1;32m    572[0m             )
[1;32m    573[0m         [38;5;28;01mreturn[39;00m credentials, effective_project_id
[0;32m--> 575[0m [38;5;28;01mraise[39;00m exceptions[38;5;241m.[39mDefaultCredentialsError(_HELP_MESSAGE)

[0;31mDefaultCredentialsError[0m: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

